---
sidebar: sidebar 
permalink: get-started/cache-intro.html 
keywords: how volume caching works, what is volume caching, bluexp 
summary: 'La memorizzazione nella cache del volume fornisce un volume persistente e scrivibile in una posizione remota.  È possibile utilizzare la memorizzazione nella cache dei volumi per velocizzare l"accesso ai dati o per scaricare il traffico dai volumi a cui si accede più frequentemente.  I volumi di cache sono ideali per carichi di lavoro ad alta intensità di lettura, soprattutto quando i client devono accedere ripetutamente agli stessi dati.' 
---
= Scopri di più sulla memorizzazione nella cache dei volumi
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La memorizzazione nella cache del volume, una funzionalità del software ONTAP 9, è una funzionalità di memorizzazione nella cache remota che semplifica la distribuzione dei file, riduce la latenza WAN avvicinando le risorse alla posizione degli utenti e delle risorse di elaborazione e abbassa i costi della larghezza di banda WAN.  La memorizzazione nella cache del volume fornisce un volume persistente e scrivibile in una posizione remota.  È possibile utilizzare la memorizzazione nella cache del volume per velocizzare l'accesso ai dati o per scaricare il traffico dai volumi a cui si accede più frequentemente.  I volumi di cache sono ideali per carichi di lavoro ad alta intensità di lettura, soprattutto quando i client devono accedere ripetutamente agli stessi dati.

Con la memorizzazione nella cache dei volumi, hai a disposizione funzionalità di memorizzazione nella cache per il cloud, in particolare per Amazon FSx for NetApp ONTAP, Cloud Volumes ONTAP e ambienti di lavoro locali.

La memorizzazione nella cache dei volumi consente inoltre alle filiali di accedere ai set di dati aziendali.  Fornendo _dati attivi_, dati a cui è necessario accedere frequentemente da più controller in un cluster, è possibile aumentare le prestazioni fornite alle applicazioni chiave.  Inoltre, memorizzando nella cache i dati importanti a livello locale per gli utenti in più sedi nel mondo, è possibile migliorare la loro collaborazione consentendo l'accesso simultaneo a set di dati centralizzati e riducendo al contempo i tempi di risposta quando accedono ai dati importanti.



== Console NetApp

La memorizzazione nella cache dei volumi è accessibile tramite la console NetApp .

NetApp Console offre una gestione centralizzata dei servizi di storage e dati NetApp in ambienti on-premise e cloud di livello aziendale. La console è necessaria per accedere e utilizzare i servizi dati NetApp . In quanto interfaccia di gestione, consente di gestire numerose risorse di archiviazione da un'unica interfaccia. Gli amministratori della console possono controllare l'accesso allo storage e ai servizi per tutti i sistemi all'interno dell'azienda.

Per iniziare a utilizzare NetApp Console non è necessaria una licenza o un abbonamento e verranno addebitati costi solo quando sarà necessario distribuire gli agenti della console nel cloud per garantire la connettività ai sistemi di storage o ai servizi dati NetApp . Tuttavia, alcuni servizi dati NetApp accessibili dalla Console sono concessi in licenza o basati su abbonamento.

Scopri di più su https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Console NetApp"] .



== Cos'è una cache?

Una cache è una posizione di archiviazione temporanea che risiede tra un host e la fonte dei dati.  L'obiettivo di una cache è quello di memorizzare le porzioni di dati sorgente a cui si accede di frequente, in modo da consentire che i dati vengano forniti più velocemente di quanto avverrebbe recuperandoli dalla sorgente.  Le cache sono particolarmente utili negli ambienti ad alta intensità di lettura, in cui i dati vengono acceduti più volte e sono condivisi da più host.  Un sistema cache è più veloce di un sistema con sorgente dati, grazie a un sistema di archiviazione più veloce e alla vicinanza dello spazio di archiviazione della cache all'host.



== Vantaggi della memorizzazione nella cache dei volumi

La memorizzazione nella cache dei volumi offre i seguenti vantaggi:

* Accelerare le prestazioni in un'infrastruttura cloud ibrida
* Eliminare i silos cloud memorizzando nella cache i dati da un provider cloud all'altro
* Costi di stoccaggio inferiori
* Collaborare tra diverse posizioni geografiche
* Capacità di adattarsi più rapidamente ai mutevoli ambienti IT
* Caching dei volumi su richiesta o in abbonamento ospitato nel cloud




== Cosa puoi fare con la memorizzazione nella cache del volume

La memorizzazione nella cache dei volumi consente di sfruttare appieno diverse tecnologie NetApp per raggiungere i seguenti obiettivi:

* Memorizza i dati nella cache da un provider cloud a un altro
* Visualizza e modifica una policy di esportazione della cache
* Ridimensiona una cache esistente
* Elimina una cache




== Costo

NetApp non addebita alcun costo per la memorizzazione nella cache dei volumi, ma è necessario verificare con il proprio provider cloud i costi applicabili per l'ingresso e l'uscita dei dati.



== Licenza

Per la memorizzazione nella cache dei volumi non sono necessarie licenze ONTAP speciali.



== Come funziona la memorizzazione nella cache del volume

Un volume cache è un volume scarsamente popolato supportato da un volume sorgente.  Il volume della cache può trovarsi sullo stesso cluster del volume di origine oppure su un cluster diverso.

Il volume della cache fornisce l'accesso ai dati nel volume di origine senza richiedere che tutti i dati siano nel volume della cache.  L'archiviazione dei dati nel volume di memorizzazione nella cache viene gestita in modo efficiente conservando solo i dati attivi (dati in funzione o utilizzati di recente).

La memorizzazione nella cache del volume legge le richieste se il volume della cache contiene i dati richiesti dal client.  In caso contrario, il servizio di memorizzazione nella cache del volume richiede i dati dal volume di origine e li memorizza prima di soddisfare la richiesta del client.  Le richieste successive di dati vengono quindi gestite direttamente dal volume della cache.  Ciò migliora le prestazioni quando si accede ripetutamente agli stessi dati, perché dopo la prima richiesta, i dati non devono più viaggiare attraverso la rete o essere forniti da un sistema sovraccarico.
